name: CI/CD for Spring Boot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build and Test with Maven
      - name: Build and Test
        run: |
          mvn clean package
          mvn test

      # Step 4: Deploy to Azure Server
      - name: Deploy to Azure Server
        run: |
          scp target/demo-0.0.1-SNAPSHOT.jar azureuser@172.166.180.49:/home/azureuser/demo.jar
          ssh azureuser@172.166.180.49 'nohup java -jar /home/azureuser/demo.jar > /home/azureuser/demo.log 2>&1 &'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
